#!/bin/sh
# Builds libvpx's VP9 decoder (BSD-3-Clause) for the iPhone app, so VP9 video
# sidecars play on iOS, which has no VP9 decoder of its own. Nothing here is
# committed: the source is cloned at a pinned tag and the static libraries,
# headers, module map, and an xcconfig land in ios/Vendor/libvpx/, which
# ios/Signing.xcconfig includes when it exists. Without this build the app
# still compiles; VP9 tracks then show the cover and a notice.
#
# Usage: ios/scripts/build-libvpx.sh
set -eu

TAG=v1.17.0
COMMIT=6df3ec34557879fff673706f4a1d9fbd0f3a6f0e
REPO=https://chromium.googlesource.com/webm/libvpx
MIN_IOS=18.0

ios=$(cd "$(dirname "$0")/.." && pwd)
vendor="$ios/Vendor"
src="$vendor/libvpx-src"
out="$vendor/libvpx"

if [ ! -d "$src/.git" ]; then
  git clone --depth 1 --branch "$TAG" "$REPO" "$src"
fi
actual=$(git -C "$src" rev-parse HEAD)
if [ "$actual" != "$COMMIT" ]; then
  echo "libvpx $TAG is $actual; expected $COMMIT" >&2
  exit 1
fi

rm -rf "$out"
mkdir -p "$out/include/vpx"
common="--disable-vp8 --disable-vp9-encoder --enable-vp9-decoder \
  --disable-examples --disable-tools --disable-docs --disable-unit-tests \
  --disable-libyuv --disable-webm-io --disable-install-bins --disable-install-docs"

# build SLICE FLAGS PLATFORM: configure libvpx's iPhone target (arm64-darwin-gcc;
# darwinNN targets are macOS) with extra compiler and linker flags, make the
# static library, and keep it only if every object carries PLATFORM.
build() {
  dir="$vendor/build-$1"
  rm -rf "$dir"
  mkdir -p "$dir" "$out/$1"
  if (cd "$dir" && LDFLAGS="$2" "$src/configure" --target=arm64-darwin-gcc $common \
        --extra-cflags="$2" >"$dir/configure.log" 2>&1 \
      && make -j"$(sysctl -n hw.ncpu)" libvpx.a >"$dir/make.log" 2>&1) \
     && [ "$(otool -lv "$dir/libvpx.a" | grep -c "platform $3")" -gt 0 ] \
     && ! otool -lv "$dir/libvpx.a" | grep "^ *platform" | grep -qv "platform $3"; then
    cp "$dir/libvpx.a" "$out/$1/libvpx.a"
    return 0
  fi
  rm -rf "$out/$1"
  return 1
}

build ios "-miphoneos-version-min=$MIN_IOS" IOS
echo "built: device slice"

# libvpx has no arm64 simulator target: aim the iPhone target at the simulator
# SDK instead. The target triple overrides configure's own deployment flag,
# which its -Werror probes would otherwise reject.
sim_sdk=$(xcrun --sdk iphonesimulator --show-sdk-path)
if build sim "-Wno-overriding-option -isysroot $sim_sdk -target arm64-apple-ios$MIN_IOS-simulator" IOSSIMULATOR; then
  echo "built: simulator slice"
else
  echo "skipped: simulator slice (see $vendor/build-sim/*.log); VP9 is unavailable in the simulator" >&2
fi

cp "$src/vpx/"*.h "$out/include/vpx/"
cp "$src/LICENSE" "$out/LICENSE"
cp "$src/PATENTS" "$out/PATENTS"
# Function-like macros do not import into Swift; wrap the decoder setup.
cat >"$out/include/vtamp_vpx.h" <<'EOF'
#ifndef VTAMP_VPX_H
#define VTAMP_VPX_H
#include "vpx/vpx_decoder.h"
#include "vpx/vp8dx.h"
static inline vpx_codec_err_t vtamp_vp9_decoder_init(vpx_codec_ctx_t *ctx, const vpx_codec_dec_cfg_t *cfg) {
    return vpx_codec_dec_init(ctx, vpx_codec_vp9_dx(), cfg, 0);
}
#endif
EOF
cat >"$out/include/module.modulemap" <<'EOF'
module vpx {
    header "vtamp_vpx.h"
    export *
}
EOF

{
  echo "// Generated by ios/scripts/build-libvpx.sh for libvpx $TAG; not committed."
  echo "SWIFT_INCLUDE_PATHS = \$(inherited) \$(SRCROOT)/Vendor/libvpx/include"
  echo "HEADER_SEARCH_PATHS = \$(inherited) \$(SRCROOT)/Vendor/libvpx/include"
  for slice in ios sim; do
    [ -f "$out/$slice/libvpx.a" ] || continue
    if [ "$slice" = ios ]; then sdk="iphoneos*"; else sdk="iphonesimulator*"; fi
    echo "LIBRARY_SEARCH_PATHS[sdk=$sdk] = \$(inherited) \$(SRCROOT)/Vendor/libvpx/$slice"
    echo "OTHER_LDFLAGS[sdk=$sdk] = \$(inherited) -lvpx"
    echo "SWIFT_ACTIVE_COMPILATION_CONDITIONS[sdk=$sdk] = \$(inherited) VTAMP_VP9"
  done
} >"$out/libvpx.xcconfig"
echo "wrote $out/libvpx.xcconfig"
